// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGn9rcvNA55AQLt2nN3OILADFjcCUuPIE',
    appId: '1:939484796037:web:8a4f4af6c5767a8cd305ec',
    messagingSenderId: '939484796037',
    projectId: 'eventmanagement-d0efd',
    authDomain: 'eventmanagement-d0efd.firebaseapp.com',
    storageBucket: 'eventmanagement-d0efd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnvhGFVt3ExcFivrCYu1KryqpHITR5cHI',
    appId: '1:939484796037:android:5cd10313a4cb0321d305ec',
    messagingSenderId: '939484796037',
    projectId: 'eventmanagement-d0efd',
    storageBucket: 'eventmanagement-d0efd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcz8CMwSsgKs02hUKqC29ZvyEmzoHASAU',
    appId: '1:939484796037:ios:86b2a7a81892a37dd305ec',
    messagingSenderId: '939484796037',
    projectId: 'eventmanagement-d0efd',
    storageBucket: 'eventmanagement-d0efd.appspot.com',
    iosBundleId: 'com.example.eventManagement1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcz8CMwSsgKs02hUKqC29ZvyEmzoHASAU',
    appId: '1:939484796037:ios:86b2a7a81892a37dd305ec',
    messagingSenderId: '939484796037',
    projectId: 'eventmanagement-d0efd',
    storageBucket: 'eventmanagement-d0efd.appspot.com',
    iosBundleId: 'com.example.eventManagement1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGn9rcvNA55AQLt2nN3OILADFjcCUuPIE',
    appId: '1:939484796037:web:809f9d827b3d2660d305ec',
    messagingSenderId: '939484796037',
    projectId: 'eventmanagement-d0efd',
    authDomain: 'eventmanagement-d0efd.firebaseapp.com',
    storageBucket: 'eventmanagement-d0efd.appspot.com',
  );
}
